#!/bin/python3

import sys

length = 1
s = '0'
while length < 1000:
    mask = (1 << length) - 1
    s = s + bin(int(s,2) ^ mask)[2:]
    length *= 2

def duplication(x):
    return s[x]

q = int(input().strip())
for a0 in range(q):
    x = int(input().strip())
    result = duplication(x)
    print(result)
