#!/bin/python3

import sys

def geometricTrick(s,n):
    triples = 0

    for j in range(1,n-1): 
        if s[j] != 'b':
            continue
        for i in range(0,j):
            jvalue = (j+1) ** 2
            if jvalue % (i+1) == 0:  
                k = int((jvalue /(i+1)) - 1)
                if k > n-1: 
                    continue
                if (s[i] == 'a' and s[k] == 'c') or (s[k] == 'a' and s[i] == 'c'):
                    triples += 1
    return triples          

n = int(input().strip())
s = input().strip()
result = geometricTrick(s,n)
print(result)
