#!/bin/python3

import sys

def twinArrays(ar1, ar2):
    ar1min1 = (ar1[0],0)
    ar1min2 = (ar1[1],1)
    if ar1min2[0] < ar1min1[0]: 
        ar1min1 = ar1min2
        ar1min2 = (ar1[0],0)
    ar2min1 = (ar2[0],0)
    ar2min2 = (ar2[1],1)
    if ar2min2[0] < ar2min1[0]: 
        ar2min1 = ar2min2
        ar2min2 = (ar2[0],0)
    for i in range(0, len(ar1)): 
        if ar1[i] < ar1min1[0]: 
            ar1min2 = ar1min1
            ar1min1 = (ar1[i],i)
        elif ar1[i] < ar1min2[0]: 
            ar1min2 = (ar1[i],i)
    for i in range(0, len(ar2)): 
        if ar2[i] < ar2min1[0]: 
            ar2min2 = ar2min1
            ar2min1 = (ar2[i],i)
        elif ar2[i] < ar2min2[0]: 
            ar2min2 = (ar2[i],i)
    if ar1min1[1] == ar2min1[1]: 
        return min(ar1min1[0] + ar2min2[0], ar1min2[0] + ar2min1[0])
    return ar1min1[0] + ar2min1[0]
        

n = int(input().strip())
ar1 = list(map(int, input().strip().split(' ')))
ar2 = list(map(int, input().strip().split(' ')))
result = twinArrays(ar1, ar2)
print(result)
